# Generated by Django 6.0 on 2025-12-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_capture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
